# Generated by Django 2.0 on 2017-12-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrcode', models.CharField(help_text='二维码', max_length=200)),
                ('code', models.CharField(help_text='编码', max_length=50)),
                ('name', models.CharField(help_text='名称', max_length=50)),
                ('specs', models.CharField(help_text='规格', max_length=200)),
                ('duty_officer', models.CharField(help_text='责任人', max_length=200)),
                ('using_man', models.CharField(help_text='使用地', max_length=200)),
                ('management_man', models.CharField(help_text='管理单位', max_length=200)),
                ('from_organize', models.CharField(help_text='转入地', max_length=200)),
                ('arrival_date', models.CharField(help_text='入厂时间', max_length=200)),
                ('hole_count', models.CharField(help_text='穴数', max_length=200)),
                ('price', models.CharField(help_text='价格', max_length=200)),
                ('supplier_id', models.CharField(help_text='供应商', max_length=200)),
            ],
        ),
    ]
