# Generated by Django 2.0 on 2017-12-22 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_jlclass_mold'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JlClass',
            new_name='JlType',
        ),
    ]
