# Generated by Django 2.0 on 2017-12-22 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_auto_20171222_0858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mold',
            old_name='jl_class',
            new_name='jl_type',
        ),
    ]
