# Generated by Django 2.0 on 2017-12-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0006_auto_20171222_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='price',
            field=models.CharField(help_text='价格', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mold',
            name='price',
            field=models.CharField(help_text='价格', max_length=200, null=True),
        ),
    ]
