# Generated by Django 2.0 on 2017-12-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0007_auto_20171222_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mold',
            name='jl_dosage',
            field=models.CharField(help_text='胶料用量', max_length=200, null=True),
        ),
    ]
