# Generated by Django 2.0 on 2017-12-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='编码', max_length=50)),
                ('name', models.CharField(help_text='名称', max_length=50)),
                ('manager', models.CharField(help_text='电话', max_length=50, null=True)),
                ('phone', models.CharField(help_text='电话', max_length=50, null=True)),
                ('address', models.CharField(help_text='地址', max_length=200, null=True)),
                ('remark', models.CharField(help_text='描述', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='编码', max_length=50)),
                ('name', models.CharField(help_text='名称', max_length=50)),
                ('phone', models.CharField(help_text='电话', max_length=50, null=True)),
                ('address', models.CharField(help_text='地址', max_length=200, null=True)),
                ('remark', models.CharField(help_text='描述', max_length=200, null=True)),
            ],
        ),
    ]
